export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_ALL_FLASH_MESSAGES = 'DELETE_ALL_FLASH_MESSAGES';
export const DELETE_BY_VALUE_FLASH_MESSAGES = 'DELETE_BY_VALUE_FLASH_MESSAGES';

export const MESSAGE_LOG_IN_SUCCESSFULY = 'You logged in successfuly. Welcome!';
export const REPORT_WAS_SUCCESSFULLY_ADDED = 'Report was successfully added';

