export const GET_CARS = 'GET_CARS';
export const GET_ALL_FREE_CARS = 'GET_ALL_FREE_CARS';
export const CAR_WAS_SUCCESSFULLY_CREATED = 'Car was successfully created!';
export const CREATE_CAR = 'CREATE_CAR';
export const DELETE_CAR = 'DELETE_CAR';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';
export const UNAUTHORIZED = '_UNAUTHORIZED';
export const CAR = 'CAR';
